spring:
  config:
    activate:
      on-profile: dev

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 30MB
      location: /app/uploads

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

app:
  upload:
    path: /app/uploads
#  frontend-url: https://dev-gorani.lab.terminal-lab.kr/