CREATE TABLE users
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    oauth_provider    VARCHAR(20)  NOT NULL,
    oauth_id          VARCHAR(100) NOT NULL,
    email             VARCHAR(100),
    nickname          VARCHAR(50)  NOT NULL,
    profile_image_url VARCHAR(500),
    role              VARCHAR(20)  NOT NULL,

    CONSTRAINT uk_oauth UNIQUE (oauth_provider, oauth_id)
);